#!/bin/bash

# this is a simple tool to help repair some problems cased by previous config

usage() {
  echo "Description:
  This is a simple tool to help repair some problems cased by previous config.

Usage:
  bash cleaner [option]
  option:
    uninstall      uninstall enable-ir-emitter
    reinstall      reinstall enable-ir-emitter"
}

uninstall() {
  # uninstall chicony-ir-toggle if it exist
  sudo rm -rf /usr/local/bin/chicony-ir-toggle
  sudo rm -rf /lib/udev/rules.d/99-ir-led.rules
  sudo rm -rf /lib/systemd/system-sleep/ir-led.sh

  
  # disable systemd service enable-ir-emitter if it exist
  if [ -f /etc/systemd/system/enable-ir-emitter.service ]
  then
    sudo systemctl stop enable-ir-emitter
    sudo systemctl disable enable-ir-emitter
  fi

  # uninstall all enable-ir-emitter if it exist
  sudo rm -rf /etc/systemd/system/enable-ir-emitter.service
  sudo rm -rf /usr/local/bin/enable-ir-emitter
}

reinstall() {
  uninstall
  cd auto || exit 1

  sudo rm -rf enable-ir-emitter
  sudo rm -rf enable-ir-emitter.service

  python3 auto-config.py
}

case $1 in
  "uninstall")
    uninstall
  ;;
  "reinstall")
    reinstall
  ;;
  *)
    usage
    exit 1
  ;;
esac

exit 0
