#!/bin/bash

# this is a simple tool to help repair some problems cased by previous config

# print usage of this script
usage() {
  echo "Description:
  This is a simple tool to help repair some problems cased by previous config.
Usage:
  bash EIE-tool [option]
  OPTS:
    help    -> print usage of this script
    remove  -> uninstall enable-ir-emitter
    repair  -> reinstall enable-ir-emitter"
}

# uninstall enable-ir-emitter
uninstall() {
  # check if chicony-ir-toggle was installed
  if [ -f /usr/local/bin/chicony-ir-toggle ]
  then
    sudo rm -rf /usr/local/bin/chicony-ir-toggle
    sudo rm -rf /lib/udev/rules.d/99-ir-led.rules
    sudo rm -rf /lib/systemd/system-sleep/ir-led.sh
  fi
  
  # disable service enable-ir-emitter
  sudo systemctl stop enable-ir-emitter
  sudo systemctl disable enable-ir-emitter

  # remove all enable-ir-emitter
  sudo rm -rf /etc/systemd/system/enable-ir-emitter.service
  sudo rm -rf /usr/local/bin/enable-ir-emitter
}

# reinstall enable-ir-emitte
reinstall() {
  # clear previous version if exist
  if [ -f /usr/local/bin/enable-ir-emitter ]
  then
    uninstall
  fi

  cd
  sudo rm -rf ./linux-enable-ir-emitter
  git clone https://github.com/EmixamPP/linux-enable-ir-emitter.git

  cd ./linux-enable-ir-emitter/auto
  sudo python3 auto-config.py
  # noticed that virtualbox require python-is-python2 :(
}

case $1 in
  help)
    usage
  ;;
  remove)
    uninstall
  ;;
  repair)
    reinstall
  ;;
  *)
    echo "use 'bash EIE-tool help' for help"
    exit 1
  ;;
esac

exit 0
