#!/bin/bash
# Autocomplete file run in bash

_linux-enable-ir-emitter() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	# Go though all cases we support
	case "${prev}" in
		"linux-enable-ir-emitter")
			opts="run configure boot delete"
			;;
		"boot")
			opts="enable disable status"
			;;
		"-d"|"--device")
            opts=$(ls /dev/video*)
			;;
 		*)
        return 0
		;;
	esac

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	return 0
}

complete -F _linux-enable-ir-emitter linux-enable-ir-emitter