#!/bin/bash

# if last uninstallation (not after update)
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # delete python cache
    rm -rf /usr/lib/linux-enable-ir-emitter/

    # delete drivers
    rm -rf /etc/linux-enable-ir-emitter/
    
    # delete systemd service
    systemctl disable linux-enable-ir-emitter &> /dev/null
    rm -f /usr/lib/systemd/system/linux-enable-ir-emitter.service
    rm -f /etc/udev/rules.d/99-linux-enable-ir-emitter.rules

    # remove executable link
    rm -f /usr/bin/linux-enable-ir-emitter

    # remove SeLinux permission
    which semanage &> /dev/null
    if [ "$?" -eq 0 ]; then
        semanage fcontext -d /usr/lib/linux-enable-ir-emitter/driver/execute-driver
        semanage fcontext -d /usr/lib/linux-enable-ir-emitter/driver/driver-generator
    fi
fi