#!/bin/bash

# if last uninstallation (not after update)
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # delete python cache
    rm -rf /usr/lib/linux-enable-ir-emitter/

    # delete drivers
    rm -rf /etc/linux-enable-ir-emitter/ # v4 and higher 
    rm -f /etc/linux-enable-ir-emitter.yaml # v3

    # delete systemd service
    systmctl disable linux-enable-ir-emitter
    rm -f /usr/lib/systemd/system/linux-enable-ir-emitter.service
    rm -f /etc/udev/rules.d/99-linux-enable-ir-emitter.rules

    # remove executable link
    rm -f /usr/bin/linux-enable-ir-emitter
fi
