name: Build for aarch64

on:
  workflow_dispatch:
  workflow_call:

env: 
  OPENCV_VERSION: "4.8.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache OpenCV dependency
      id: cache-opencv
      uses: actions/cache@v3
      with:
        path: opencv_build
        key: opencv-${{ env.OPENCV_VERSION }}_aarch64

    - name: Build + Create tarball
      uses: uraimo/run-on-arch-action@v2
      with:
        env: |
          OPENCV_VERSION: ${{ env.OPENCV_VERSION }}
        arch: aarch64
        distro: ubuntu_latest
        githubToken: ${{ github.token }}
        setup: |
          mkdir -p "${PWD}/artifacts"
          mkdir -p "${PWD}/opencv_build"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
          --volume "${PWD}/opencv_build:/opencv_build"
        install: |
          apt-get update -y
          apt-get install -y python3 python3-pip python3-setuptools python3-wheel ninja-build g++ pkg-config curl cmake libgtk-3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install meson

        run: |
          [ "$(ls /opencv_build)" ] || curl https://raw.githubusercontent.com/EmixamPP/opencv-tiny/main/build.sh | bash -s ${OPENCV_TINY_VERSION} /opencv-tiny
          
          meson setup build
          meson configure build -Dlibdir=lib64
          meson compile -C build

          DESTDIR=install_dir meson install -C build
          chown -R root:root build/install_dir
          tar -czvf /artifacts/linux-enable-ir-emitter.aarch64.tar.gz -C build/install_dir .

    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: linux-enable-ir-emitter.aarch64.tar.gz
        path: artifacts/linux-enable-ir-emitter.aarch64.tar.gz
        if-no-files-found: error
