name: "clang-format"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson gcc pkg-config libgtk-3-dev cmake

      - name: Cache lib dependencies
        uses: actions/cache@v4
        with:
          path: .github/workflows/deps/install_dir
          key: ${{ hashFiles('.github/workflows/deps/CMakeLists.txt') }}

      - name: Setup
        run: |
          meson setup build --prefer-static --pkg-config-path=$(find .github -name "pkgconfig")

      - name: Check
        run: |
          ninja clang-format -C build
