name: "clang-tidy"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools python3-wheel ninja-build g++ pkg-config libgtk-3-dev
          python -m pip install meson

      - name: Cache lib dependencies
        uses: actions/cache@v4
        with:
          path: .github/workflows/deps/install_dir
          key: ${{ hashFiles('.github/workflows/deps/CMakeLists.txt') }}

      - name: Setup
        run: |
          meson setup build --prefer-static --pkg-config-path=$(find .github -name "pkgconfig")

      - name: Check
        run: |
          ninja clang-tidy -C build
