name: "C++ Lint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: C++ linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-setuptools python3-wheel ninja-build g++ pkg-config clang-tidy libgtk-3-dev libopencv-dev libyaml-cpp-dev
          python -m pip install --upgrade pip
          python -m pip install meson

      - name: Setup
        run: |
          meson setup build 

      - name: Lint
        run: |
          ninja clang-tidy -C build
      