name: "C++ Lint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-setuptools python3-wheel ninja-build g++ clang-tidy libgtk-3-dev libopencv-video-dev libopencv-video-dev
          python -m pip install --upgrade pip
          python -m pip install meson

      - name: Setup
        run: |
          meson setup build
          meson configure build -Dwerror=false
          meson compile -C build

      - name: Lint
        run: |
          ninja clang-tidy -C build
      