name: "C++ Lint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: C++ linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load dependencies versions
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '.github/workflows/deps/version.env'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-setuptools python3-wheel
          python -m pip install meson

      - name: Cache lib dependencies
        uses: actions/cache@v4
        with:
          path: .github/workflows/deps/install_dir
          key: ${{ env.OPENCV_GIT_TAG }}-${{ env.YAML_GIT_TAG }}-${{ env.ARGPARSE_GIT_TAG }}
          fail-on-cache-miss: true

      - name: Setup
        run: |
          meson setup build --prefer-static --pkg-config-path=$(find .github -name "pkgconfig")

      - name: Lint
        run: |
          ninja clang-tidy -C build
