name: Build and Lint

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install -y meson clang-tidy
          pip install pyright
          curl -L https://github.com/EmixamPP/opencv-tiny/raw/main/opencv-4.7.0.tar.xz | tar -xJ

      - name: Run meson
        run: |
          meson setup build --pkg-config-path opencv-4.7.0/lib64/pkgconfig 
          meson compile -C build

      - name: Run clang-tidy
        run: |
          ninja clang-tidy -C build

      - name: Run pyright
        run: |
          pyright $(git ls-files '*.py')
