name: Build and Lint

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install -y libopencv-dev meson clang-tidy
          pip install pyright

      - name: Run meson
        run: |
          meson setup build
          meson compile -C build

      - name: Run clang-tidy
        run: |
          ninja clang-tidy -C build

      - name: Run pylint
        run: |
          python3 -m pyright $(git ls-files '*.py')
