name: "Pull Request"

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  cpp-lint:
    needs:
      - build
    uses: ./.github/workflows/cpp-lint.yml

  comment:
    name: Bot comment
    needs:
      - build
      - cpp-lint
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: bot_comment
          mode: recreate
          message: |
            ## :arrow_right: Commit ${{ github.event.pull_request.head.sha }}

            ## :clipboard: [Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ## :mag: Linting results: ${{ needs.cpp-lint.result == 'success' && ':heavy_check_mark:' || ':x:' }}

            ## :hammer_and_wrench: Building result: ${{ needs.build.result == 'success' && ':heavy_check_mark:' || ':x:' }}
          
            ## :package: Artifacts:
            If the building step was successfull:
            1. Download the tarball in the artifacts section [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            2. [Uninstall the previous version](docs/uninstallation.md) if you have one
            3. Unzip: `unzip linux-enable-ir-emitter*.tar.gz.zip`
            4. Install: `sudo tar -C / --no-same-owner -m -h -vxzf linux-enable-ir-emitter*.tar.gz`
            5. Enable the boot service: `sudo systemctl enable --now linux-enable-ir-emitter`
