name: Build, Lint, Pack

on:
  workflow_dispatch:
  pull_request:
  
jobs:         
  ci:
    uses: ./.github/workflows/ci.yml

  pack:
      needs: ci
      runs-on: ubuntu-latest
      steps: 
      - name: Create tarball
        run: |
          DESTDIR=install_dir meson install -C build
          tar -czvf build/linux-enable-ir-emitter.tar.gz -C build/install_dir .

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: linux-enable-ir-emitter.tar.gz
          path: build/linux-enable-ir-emitter.tar.gz
          if-no-files-found: error
