name: "Pull Request"

on:
  pull_request:
  
jobs:
  py-lint:
    uses: ./.github/workflows/py-lint.yml      
  
  cpp-lint:
    uses: ./.github/workflows/cpp-lint.yml

  build:
    uses: ./.github/workflows/build.yml
  
  comment:
    name: Bot comment
    needs: 
      - py-lint
      - cpp-lint
      - build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: bot_comment
          mode: recreate
          GITHUB_TOKEN: ${{ github.token }}
          message: |
            ## :arrow_right: Commit ${{ github.event.pull_request.head.sha }}

            ## :mag: Linting results:
            ${{ needs.py-lint.result == 'success' && ':heavy_check_mark:' || ':x:' }} [Python Linting](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ needs.py-lint.outputs.id }})

            ${{ needs.cpp-lint.result == 'success' && ':heavy_check_mark:' || ':x:' }} [C++ Linting](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ needs.cpp-lint.outputs.id }})

            ## :hammer_and_wrench: Building result:
            ${{ needs.build.result == 'success' && ':heavy_check_mark:' || ':x:' }} [Building](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ needs.build.outputs.id }})

            ## :package: Tarballs:
            If the building step was successfull, you can download the appropriate tarball in the artifacts section [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            Unzip and then execute `sudo tar -C / --no-same-owner -h -xzf linux-enable-ir-emitter*.tar.gz`. 
