name: Pull request

on: 
  pull_request:

jobs:         
  ci:
    uses: ./.github/workflows/main.yml
  
  comment-tarball:
    runs-on: ubuntu-latest
    needs: ci
    steps:     
      - name: Send tarball link
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tarballLink = $(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" | \
            jq -r '.artifacts[0].archive_download_url')

            const downloadMsg = `The tarball is available for download [here](${tarballLink}).`
            const installMsg = 'To install it, execute \`sudo tar -C / --no-same-owner -h -xzf linux-enable-ir-emitter.tar.gz\`.'
            
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${downloadMsg}\n${installMsg}`
            });
