name: "Python Lint"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  py-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyright

      - name: Lint
        run: |
          pyright $(git ls-files '*.py')
      